### ISSUE TITLE
[Bug] Hello World sample workflow cannot run

### ISSUE THREAD

**Issue by rupalivohra** [temporalio/samples-typescript#22]
### Describe the bug

Attempting to run the hello-world workflow throws an error in the @temporalio/client package.

### To Reproduce

1. Run `npx @temporalio/create@latest ./example-temporal-node --sample hello-world` to fetch the example
2. Start the Temporal server: `docker-compose up`.
3. Start the worker: `npm run start.watch`.
4. Try to run the workflow: `npm run workflow`.

### Expected behavior

I expect the workflow to run as described in the [documentation](https://docs.temporal.io/docs/node/introduction/#step-2-run-your-workflow).

### Screenshots/Terminal output

```
example-temporal-node % npm run workflow

> example-temporal-node@0.1.0 workflow /Users/rupalivohra/code/convoyinc/example-temporal-node
> ts-node src/exec-workflow.ts

<redacted/path>/example-temporal-node/node_modules/@temporalio/client/lib/workflow-client.js:65
        const interceptors = (this.options.interceptors.calls ?? []).map((ctor) => ctor({ workflowId: compiledOptions.workflowId }));
                                                               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/rupalivohra/code/convoyinc/example-temporal-node/node_modules/@temporalio/client/src/index.ts:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example-temporal-node@0.1.0 workflow: `ts-node src/exec-workflow.ts`
npm ERR! Exit status 1
```

### Versions

Temporalio Client version from yarn.lock:
```
"@temporalio/client@^0.8.0":
  version "0.8.0"
  resolved "https://packages.convoy.com/artifactory/api/npm/npm/@temporalio/client/-/client-0.8.0.tgz#1e659089a6dd2c66a2ea5bb2e08b137b29e5dc8e"
  integrity sha1-HmWQiabdLGai6luy4IsTeynl3I4=
  dependencies:
    "@grpc/grpc-js" "^1.3.7"
    "@temporalio/common" "^0.4.0"
    "@temporalio/proto" "^0.3.3"
    ms "^2.1.3"
    protobufjs "^6.11.2"
    uuid "^8.3.2"
```

**Comment by lorensr** [comment]
Hi Rupali, thanks for reporting. When I do your repro steps with node 16.6.2, it works. What node version are you on? We support 14+.

**Comment by lorensr** [comment]
We just added them! They should show up in generated projects when the next version of `@temporalio/create` is released.

Np!
