### ISSUE TITLE
[Bug] activites-cancellation-heartbeating throws TypeError from @temporalio/activity/src/index.ts

### ISSUE THREAD

**Issue by kbroton** [temporalio/samples-typescript#309]
### What are you really trying to do?
I am trying to run the worker and workflow for the `./samples-typescript/activities-cancellation-heartbeating` example. This occurs both in Gitpod and locally in VS Code.

### Describe the bug
The example code fails to run and throws a Typescript TypeError.

```
2023-11-17T17:42:05.017Z [WARN] Activity failed {
  isLocal: false,
  attempt: 3,
  namespace: 'default',
  taskToken: 'CiQxYWY1NGU2OS1lYzZkLTQ2OGMtYWZlNy0zMWMxY2I3NGU2MzkSG2NhbmNlbGxhdGlvbi1oZWFydGJlYXRpbmctMBokOTM2NWI4MjQtYTZhOC00M2FmLWFkMjItMGI2YTRiODc0OTY5IAUoAzIBMUIMZmFrZVByb2dyZXNz',
  workflowId: 'cancellation-heartbeating-0',
  workflowRunId: '9365b824-a6a8-43af-ad22-0b6a4b874969',
  workflowType: 'runCancellableActivity',
  activityId: '1',
  activityType: 'fakeProgress',
  taskQueue: 'cancellation-heartbeating',
  error: TypeError: Cannot read properties of undefined (reading 'cancelled')
      at sleep (/workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/activity/src/index.ts:313:31)
      at Activity.fakeProgress [as fn] (/workspace/samples-typescript/activities-cancellation-heartbeating/src/activities.ts:14:13)
      at Activity.execute (/workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/worker/src/activity.ts:72:23)
      at /workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/worker/src/activity.ts:78:97
      at ActivityInboundLogInterceptor.execute (/workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/worker/src/activity-log-interceptor.ts:66:20)
      at next (/workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/common/src/interceptors.ts:29:59)
      at /workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/worker/src/activity.ts:79:30
      at AsyncLocalStorage.run (node:async_hooks:346:14)
      at Activity.run (/workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/worker/src/activity.ts:76:30)
      at /workspace/samples-typescript/activities-cancellation-heartbeating/node_modules/@temporalio/worker/src/worker.ts:985:48,
  durationMs: 0
}
```

### Minimal Reproduction
Clone the repo locally or in GitPod, run as described in `./samples-typescript/activities-cancellation-heartbeating/README.md`.

### Environment/Versions

GitPod or M1 mac, latest temporal version on docker.

### Additional context
N/a

**Comment by giuliohome** [comment]
Same issue here when I've tried running the [worker-specific-task-queues](../tree/main/worker-specific-task-queues//#worker-specific-task-queues) from Gitpod.

The activity fails with the following log:

```
2023-11-19T14:20:40.545Z [WARN] Activity failed {
  isLocal: false,
  attempt: 2,
  namespace: 'default',
  taskToken: 'CiQ3Y2M4ODU2My0wMzVmLTQ4NDQtYTQ5Yy1iNjAyOTY1OWUwYWMSEWZpbGUtcHJvY2Vzc2luZy0wGiQ4N2U0ZGYyYi05NWU4LTQzNmYtOGFlOS0xNTdkYTAwNjQ3YzkgOygCMgIxMEIeZG93bmxvYWRGaWxlVG9Xb3JrZXJGaWxlU3lzdGVt',
  workflowId: 'file-processing-0',
  workflowRunId: '87e4df2b-95e8-436f-8ae9-157da00647c9',
  workflowType: 'fileProcessingWorkflow',
  activityId: '10',
  activityType: 'downloadFileToWorkerFileSystem',
  taskQueue: '27b0d92b-e33d-4df4-93df-d89257b516d9',
  error: TypeError: Cannot read properties of undefined (reading 'cancelled')
      at sleep (/workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/activity/src/index.ts:313:31)
      at Activity.downloadFileToWorkerFileSystem [as fn] (/workspace/samples-typescript/worker-specific-task-queues/src/activities.ts:21:13)
      at Activity.execute (/workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/worker/src/activity.ts:72:23)
      at /workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/worker/src/activity.ts:78:97
      at ActivityInboundLogInterceptor.execute (/workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/worker/src/activity-log-interceptor.ts:66:20)
      at next (/workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/common/src/interceptors.ts:29:59)
      at /workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/worker/src/activity.ts:79:30
      at AsyncLocalStorage.run (node:async_hooks:346:14)
      at Activity.run (/workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/worker/src/activity.ts:76:30)
      at /workspace/samples-typescript/worker-specific-task-queues/node_modules/@temporalio/worker/src/worker.ts:985:48,
  durationMs: 0
}
```

**Comment by giuliohome** [comment]
The problem is due to the way that `sleep` is [imported by destructuring the current context](https://github.com/temporalio/samples-typescript/blob/98853010a11fc3c8a3dda49c7f0cdaa0e134fb32/activities-cancellation-heartbeating/src/activities.ts#L5).

I've written the [full explanation here](https://github.com/temporalio/samples-typescript/pull/311#issuecomment-1817973070):
