### ISSUE TITLE
[Bug] progress is not a function

### ISSUE THREAD

**Issue by lorensr** [temporalio/samples-typescript#56]
I think this used to work for me, not sure what happened. workflowsPath and the export looks right. When we figure it out, let's also improve error messages.

### Describe the bug

When I run `timer-progress`, the worker logs this:

```
2021-11-07T06:06:09.780Z [WARN] [temporal_sdk_core::worker] Task not found when completing: status: NotFound, message: "Workflow executionsRow not found.  WorkflowId: tutorial, RunId: 8e997415-ed60-4467-bead-2c44b3bed03a", details: [8, 5, 18, 100, 87, 111, 114, 107, 102, 108, 111, 119, 32, 101, 120, 101, 99, 117, 116, 105, 111, 110, 115, 82, 111, 119, 32, 110, 111, 116, 32, 102, 111, 117, 110, 100, 46, 32, 32, 87, 111, 114, 107, 102, 108, 111, 119, 73, 100, 58, 32, 116, 117, 116, 111, 114, 105, 97, 108, 44, 32, 82, 117, 110, 73, 100, 58, 32, 56, 101, 57, 57, 55, 52, 49, 53, 45, 101, 100, 54, 48, 45, 52, 52, 54, 55, 45, 98, 101, 97, 100, 45, 50, 99, 52, 52, 98, 51, 98, 101, 100, 48, 51, 97, 26, 66, 10, 64, 116, 121, 112, 101, 46, 103, 111, 111, 103, 108, 101, 97, 112, 105, 115, 46, 99, 111, 109, 47, 116, 101, 109, 112, 111, 114, 97, 108, 46, 97, 112, 105, 46, 101, 114, 114, 111, 114, 100, 101, 116, 97, 105, 108, 115, 46, 118, 49, 46, 78, 111, 116, 70, 111, 117, 110, 100, 70, 97, 105, 108, 117, 114, 101], metadata: MetadataMap { headers: {"content-type": "application/grpc"} } 
```

and the client throws:

```
$ nr workflow

> temporal-progress@0.1.0 workflow
> ts-node src/execute-workflow.ts

Error: 4 DEADLINE_EXCEEDED: context deadline exceeded
    at Object.callErrorFromStatus (/Users/me/gh/samples-typescript/timer-progress/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/timer-progress/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at /Users/me/gh/samples-typescript/timer-progress/node_modules/@grpc/grpc-js/src/call-stream.ts:182:27
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/timer-progress/node_modules/@temporalio/client/src/grpc-retry.ts:106:15)
    at InterceptingListenerImpl.onReceiveStatus (/Users/me/gh/samples-typescript/timer-progress/node_modules/@grpc/grpc-js/src/call-stream.ts:178:19)
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/timer-progress/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/Users/me/gh/samples-typescript/timer-progress/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /Users/me/gh/samples-typescript/timer-progress/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 4,
  details: 'context deadline exceeded',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }
}
```

and the UI shows:

![image](https://user-images.githubusercontent.com/251288/140634770-d4c6d5bc-adc2-4d5e-bdaa-9214231e3836.png)

**Comment by lorensr** [comment]
The bug was I still had another worker running in another sample 😄 Moving the error improvement FR to the SDK repo.
