### ISSUE TITLE
[Bug] monorepo-folders example crashes

### ISSUE THREAD

**Issue by vkarpov15** [temporalio/samples-typescript#85]
### What are you really trying to do?

Trying to run the monorepo-folders example on my machine following the instructions in the README.

### Describe the bug

Got the below error:

```
[frontend] ℹ ｢wds｣: Project is running at http://192.168.0.49/
[frontend] ℹ ｢wds｣: webpack output is served from 
[frontend] ℹ ｢wds｣: Content not from webpack is served from /home/val/Workspace/temporalio/samples-typescript/monorepo-folders/packages/frontend-ui/public
[frontend] ℹ ｢wds｣: 404s will fallback to /
[frontend] Starting the development server...
[frontend] 
[worker] /home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/ts-node/src/index.ts:750
[worker]     return new TSError(diagnosticText, diagnosticCodes);
[worker]            ^
[worker] TSError: ⨯ Unable to compile TypeScript:
[worker] worker.ts(2,29): error TS2307: Cannot find module 'temporal-workflows/lib/all-activities' or its corresponding type declarations.
[worker] 
[worker]     at createTSError (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/ts-node/src/index.ts:750:12)
[worker]     at reportTSError (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/ts-node/src/index.ts:754:19)
[worker]     at getOutput (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/ts-node/src/index.ts:941:36)
[worker]     at Object.compile (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/ts-node/src/index.ts:1243:30)
[worker]     at Module.m._compile (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/ts-node/src/index.ts:1370:30)
[worker]     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[worker]     at Object.require.extensions.<computed> [as .ts] (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/ts-node/src/index.ts:1374:12)
[worker]     at Module.load (internal/modules/cjs/loader.js:950:32)
[worker]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[worker]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
[worker]   diagnosticText: "worker.ts(2,29): error TS2307: Cannot find module 'temporal-workflows/lib/all-activities' or its corresponding type declarations.\n",
[worker]   diagnosticCodes: [ 2307 ]
[worker] }
[worker] [nodemon] app crashed - waiting for file changes before starting...
[frontend] Compiled successfully!
[frontend] 
[frontend] You can now view frontend-ui in the browser.
[frontend] 
[frontend]   Local:            http://localhost:3000
[frontend]   On Your Network:  http://192.168.0.49:3000
[frontend] 
[frontend] Note that the development build is not optimized.
[frontend] To create a production build, use npm run build.
[frontend] 
[api-server] TypeError: Cannot read property 'QUERY_REJECT_CONDITION_UNSPECIFIED' of undefined
[api-server]     at defaultWorkflowClientOptions (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/@temporalio/client/src/workflow-client.ts:160:70)
[api-server]     at new WorkflowClient (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/@temporalio/client/src/workflow-client.ts:207:25)
[api-server]     at Object.runWorkflow (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/packages/backend-apis/temporal-client.ts:9:18)
[api-server]     at /home/val/Workspace/temporalio/samples-typescript/monorepo-folders/packages/backend-apis/server.ts:14:41
[api-server]     at Layer.handle [as handle_request] (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/express/lib/router/layer.js:95:5)
[api-server]     at next (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/express/lib/router/route.js:137:13)
[api-server]     at Route.dispatch (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/express/lib/router/route.js:112:3)
[api-server]     at Layer.handle [as handle_request] (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/express/lib/router/layer.js:95:5)
[api-server]     at /home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/express/lib/router/index.js:281:22
[api-server]     at Function.process_params (/home/val/Workspace/temporalio/samples-typescript/monorepo-folders/node_modules/express/lib/router/index.js:335:12)
[api-server] [nodemon] app crashed - waiting for file changes before starting...
[frontend] Proxy error: Could not proxy request /api/workflow from localhost:3000 to http://localhost:4000.
[frontend] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
[frontend] 

```

### Minimal Reproduction

monorepo-folders

### Environment/Versions

yarn 1.22.17
ubuntu 20.04

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux] ubuntu 20.04
- Temporal Version: [e.g. 1.14.0?] and/or SDK version: SDK 0.16.4, temporalio/docker-compose v1.13.1
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by sw-yx** [comment]
i get even other errors when running yarn start:

```
 from /Users/swyx/Work/Temporal/testnodesdk/mood/packages/frontend-ui/public
[frontend] ℹ ｢wds｣: 404s will fallback to /
[frontend] Starting the development server...
[frontend] 
[frontend] /Users/swyx/Work/Temporal/testnodesdk/mood/node_modules/react-scripts/scripts/start.js:19
[frontend]   throw err;
[frontend]   ^
[frontend] 
[frontend] TypeError: Cannot read property 'createSnapshot' of undefined
[frontend]     at /Users/swyx/Work/Temporal/testnodesdk/mood/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
[frontend]     at new Promise (<anonymous>)
[frontend]     at Object.createSnapshot (/Users/swyx/Work/Temporal/testnodesdk/mood/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
[frontend]     at /Users/swyx/Work/Temporal/testnodesdk/mood/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

i dont understand how this example deteriorated so quickly from a working state

**Comment by lorensr** [comment]
@swyx I don't get your createSnapshot error, but Val's error is due to this line in 24d8c6c :

![image](https://user-images.githubusercontent.com/251288/148895558-37414a7f-9350-46ed-8f84-e489a2964096.png)


```
cd monorepo-folders
git checkout 2a02
yarn build.workflows
# succeeds
git checkout 24d8c6c
rm -rf packages/temporal-workflows/lib/
yarn build.workflows
# fails
```

You probably missed the `rm -rf packages/temporal-workflows/lib/` step while developing, so the build no-op "succeeded" because `lib` was already present.
