### ISSUE TITLE
[Bug] --list-samples is an unknown argument for the `@temporalio/create` package

### ISSUE THREAD

**Issue by rupalivohra** [temporalio/samples-typescript#89]
### Describe the bug

The [documentation](https://docs.temporal.io/docs/node/package-initializer/#optional-flags) identifies `--list-samples` as an optional arg to the sample creation package. If you try to use this arg, however, the package throws an error saying that it doesn't know what that option is.

### To Reproduce

Run `npx @temporalio/create@latest hello-world --list-samples` or `npx @temporalio/create@latest --list-samples` from your terminal.

### Expected behavior

I expect to see a list of available samples I can bootstrap.

### Screenshots/Terminal output

```
% npx @temporalio/create@latest hello-world --list-samples      
Need to install the following packages:
  @temporalio/create@latest
Ok to proceed? (y) y
ArgError: unknown or unexpected option: --list-samples
    at arg (/Users/rupalivohra/.npm/_npx/84edb3507a773a27/node_modules/arg/index.js:132:13)
    at init (/Users/rupalivohra/.npm/_npx/84edb3507a773a27/node_modules/@temporalio/create/lib/index.js:124:52)
    at Object.<anonymous> (/Users/rupalivohra/.npm/_npx/84edb3507a773a27/node_modules/@temporalio/create/lib/index.js:135:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ARG_UNKNOWN_OPTION'
}

```

**Comment by lorensr** [comment]
Yep can be closed.
