### ISSUE TITLE
[Bug] devcontainer not running appropriately

### ISSUE THREAD

**Issue by kenfdev** [temporalio/samples-typescript#92]
### What are you really trying to do?

First of all, thanks for this awesome repository to test Temporal.
That said, I'm trying to run the `hello-world` sample via VSCode devcontainer.

### Describe the bug

Not sure if this is a bug but I cannot view the workflow from the temporal UI. First of all, there's probably a typo in the docker-compose.yml where it says `depends_on: temporal` here:

https://github.com/temporalio/samples-typescript/blob/9052df328b52a7d73289c9dc12e42cd2082d1a27/.devcontainer/docker-compose.yml#L50

I assume this should be `temporalite`. After editing this, the devcontainer spins up and I can access the temporal UI.

Unfortuantely, a `500 Internal Server Error` keeps on showing up in the UI.

![image](https://user-images.githubusercontent.com/3941889/150343940-32c3bb70-bcd7-4aa8-80ba-f01c1af479f2.png)

If I look at the logs for the `temporalite` container, I see some errors happening as follows:

```
{"level":"debug","ts":"2022-01-20T13:03:55.542Z","msg":"Poll workflow task queue.","service":"frontend","wf-namespace":"temporal-system","wf-namespace-id":"32049b68-7872-4094-8e63-d0dd59896a83","logging-call-at":"workflowHandler.go:777"}
{"level":"debug","ts":"2022-01-20T13:03:55.544Z","msg":"Received PollWorkflowTaskQueue for taskQueue","service":"matching","component":"matching-engine","wf-task-queue-name":"125f23ab927c:69aa0d3b-a789-4202-9578-a054269db107","logging-call-at":"matchingEngine.go:349"}
{"level":"error","ts":"2022-01-20T13:03:56.850Z","msg":"Panic is captured","service":"frontend","sys-stack-trace":"goroutine 416646 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngo.temporal.io/server/common/log.CapturePanic({0x384e078, 0xc0009c7a10}, 0xc00142aba8)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/log/panic.go:49 +0x8e\npanic({0x2101780, 0xc000043560})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x215\ngo.temporal.io/server/common/persistence/visibility/store/standard.(*valuesInterceptor).Values(0xc0026146a8, {0xc000492d50, 0x382a3d0}, {0xc0024ff140, 0x0, 0x0})\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/standard/query_interceptors.go:109 +0x8de\ngo.temporal.io/server/common/persistence/visibility/store/query.(*comparisonExprConverter).Convert(0xc0018fc450, {0x382a440, 0xc0013f1b80})\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:444 +0x207\ngo.temporal.io/server/common/persistence/visibility/store/query.(*WhereConverter).Convert(0x0, {0x382a440, 0xc0013f1b80})\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:265 +0x1da\ngo.temporal.io/server/common/persistence/visibility/store/query.(*Converter).convertSelect(0xc00228e160, 0xc0018add40)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:227 +0x7f\ngo.temporal.io/server/common/persistence/visibility/store/query.(*Converter).ConvertSql(0x22a81a9, {0xc000a00500, 0xc000efc970})\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:213 +0x5f\ngo.temporal.io/server/common/persistence/visibility/store/query.(*Converter).ConvertWhereOrderBy(0x4a4d901, {0xc0013ddaa0, 0x1a42abc})\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:198 +0xdc\ngo.temporal.io/server/common/persistence/visibility/store/standard.(*converter).GetFilter(0xc0024ff0e0, {0xc0013ddaa0, 0x9a2785f37d})\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/standard/converter.go:70 +0x2d\ngo.temporal.io/server/common/persistence/visibility/store/standard.(*standardStore).ListWorkflowExecutions(0xc0008882e0, 0xc0018be5a0)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/standard/visibility_store.go:128 +0x3c\ngo.temporal.io/server/common/persistence/visibility.(*visibilityManagerImpl).ListWorkflowExecutions(0xc000077d60, 0x43)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/visibility_manager_impl.go:181 +0x29\ngo.temporal.io/server/common/persistence/visibility.(*visibilityManagerRateLimited).ListWorkflowExecutions(0xc000886960, 0x50)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/visibility_manager_rate_limited.go:144 +0x4a\ngo.temporal.io/server/common/persistence/visibility.(*visibilityManagerMetrics).ListWorkflowExecutions(0xc00088c300, 0xc000492bc0)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/visiblity_manager_metrics.go:147 +0x5b\ngo.temporal.io/server/service/frontend.(*WorkflowHandler).ListWorkflowExecutions(0xc0007e3d40, {0x3829870, 0xc0018fc030}, 0xc0013f14c0)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/workflowHandler.go:2275 +0x422\ngo.temporal.io/server/service/frontend.(*DCRedirectionHandlerImpl).ListWorkflowExecutions.func2({0x22823d8, 0x6})\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/dcRedirectionHandler.go:405 +0x14c\ngo.temporal.io/server/service/frontend.(*NoopRedirectionPolicy).WithNamespaceRedirect(0xc0006730e0, {0xc000efcce8, 0x1145dcc}, {0x8, 0xc000efcce0}, {0x0, 0xf58}, 0x0)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/dcRedirectionPolicy.go:118 +0x26\ngo.temporal.io/server/service/frontend.(*DCRedirectionHandlerImpl).ListWorkflowExecutions(0xc0006730e0, {0x3829870, 0xc0018fc030}, 0xc0013f14c0)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/dcRedirectionHandler.go:401 +0x2d9\ngo.temporal.io/api/workflowservice/v1._WorkflowService_ListWorkflowExecutions_Handler.func1({0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/go.temporal.io/api@v1.7.0/workflowservice/v1/service.pb.go:1482 +0x7b\ngo.temporal.io/server/common/authorization.(*interceptor).Interceptor(0xc0007eea50, {0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0}, 0xc00228e060, 0xc002614438)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/authorization/interceptor.go:152 +0x637\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1116 +0x5b\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceCountLimitInterceptor).Intercept(0xc000717800, {0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0}, 0x16, 0xc0013f1500)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_count_limit.go:98 +0x1e3\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceRateLimitInterceptor).Intercept(0xc000882b10, {0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0}, 0x23171e5, 0xc0013f1500)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_rate_limit.go:88 +0x1fa\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngo.temporal.io/server/common/rpc/interceptor.(*RateLimitInterceptor).Intercept(0xc00081cd38, {0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0}, 0x46, 0xc0013f1500)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/rate_limit.go:83 +0x1a5\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceValidatorInterceptor).Intercept(0x380f3e8, {0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0}, 0xc00228e060, 0xc0013f1500)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_validator.go:113 +0xc6\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0018fc030}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngo.temporal.io/server/common/rpc/interceptor.(*TelemetryInterceptor).Intercept(0x0, {0x3829870, 0xc0008c1c80}, {0x21cac40, 0xc0013f14c0}, 0x20e1540, 0xc0013f1500)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/telemetry.go:108 +0x22e\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0008c1c80}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngo.temporal.io/server/common/metrics.NewServerMetricsContextInjectorInterceptor.func1({0x3829870, 0xc0008c1c50}, {0x21cac40, 0xc0013f14c0}, 0xc001b73fc8, 0xc0013f1500)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/metrics/grpc.go:66 +0x7c\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0008c1c50}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngo.temporal.io/server/common/rpc.ServiceErrorInterceptor({0x3829870, 0xc0008c1c50}, {0x21cac40, 0xc0013f14c0}, 0x4ddc20, 0xc001068778)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/grpc.go:131 +0x34\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0008c1c50}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceLogInterceptor).Intercept(0x100000000000000, {0x3829870, 0xc0008c1c50}, {0x21cac40, 0xc0013f14c0}, 0x40, 0xc00005cc00)\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_logger.go:84 +0x74f\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x3829870, 0xc0008c1c50}, {0x21cac40, 0xc0013f14c0})\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119 +0x83\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1({0x3829870, 0xc0008c1c50}, {0x21cac40, 0xc0013f14c0}, 0xc00228e060, 0xc002614438)\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1121 +0x12b\ngo.temporal.io/api/workflowservice/v1._WorkflowService_ListWorkflowExecutions_Handler({0x22375c0, 0xc0006730e0}, {0x3829870, 0xc0008c1c50}, 0xc001c13f80, 0xc000077bc0)\n\t/go/pkg/mod/go.temporal.io/api@v1.7.0/workflowservice/v1/service.pb.go:1484 +0x138\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc000499dc0, {0x386b498, 0xc002469800}, 0xc001c026c0, 0xc00095efc0, 0x497b410, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf\ngoogle.golang.org/grpc.(*Server).handleStream(0xc000499dc0, {0x386b498, 0xc002469800}, 0xc001c026c0, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2()\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:921 +0x98\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:919 +0x294\n","error":"runtime error: index out of range [1] with length 1","logging-call-at":"panic.go:51","stacktrace":"go.temporal.io/server/common/log.(*zapLogger).Error\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/log/zap_logger.go:142\ngo.temporal.io/server/common/log.CapturePanic\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/log/panic.go:51\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:1038\nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:90\ngo.temporal.io/server/common/persistence/visibility/store/standard.(*valuesInterceptor).Values\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/standard/query_interceptors.go:109\ngo.temporal.io/server/common/persistence/visibility/store/query.(*comparisonExprConverter).Convert\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:444\ngo.temporal.io/server/common/persistence/visibility/store/query.(*WhereConverter).Convert\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:265\ngo.temporal.io/server/common/persistence/visibility/store/query.(*Converter).convertSelect\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:227\ngo.temporal.io/server/common/persistence/visibility/store/query.(*Converter).ConvertSql\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:213\ngo.temporal.io/server/common/persistence/visibility/store/query.(*Converter).ConvertWhereOrderBy\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/query/converter.go:198\ngo.temporal.io/server/common/persistence/visibility/store/standard.(*converter).GetFilter\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/standard/converter.go:70\ngo.temporal.io/server/common/persistence/visibility/store/standard.(*standardStore).ListWorkflowExecutions\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/store/standard/visibility_store.go:128\ngo.temporal.io/server/common/persistence/visibility.(*visibilityManagerImpl).ListWorkflowExecutions\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/visibility_manager_impl.go:181\ngo.temporal.io/server/common/persistence/visibility.(*visibilityManagerRateLimited).ListWorkflowExecutions\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/visibility_manager_rate_limited.go:144\ngo.temporal.io/server/common/persistence/visibility.(*visibilityManagerMetrics).ListWorkflowExecutions\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/persistence/visibility/visiblity_manager_metrics.go:147\ngo.temporal.io/server/service/frontend.(*WorkflowHandler).ListWorkflowExecutions\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/workflowHandler.go:2275\ngo.temporal.io/server/service/frontend.(*DCRedirectionHandlerImpl).ListWorkflowExecutions.func2\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/dcRedirectionHandler.go:405\ngo.temporal.io/server/service/frontend.(*NoopRedirectionPolicy).WithNamespaceRedirect\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/dcRedirectionPolicy.go:118\ngo.temporal.io/server/service/frontend.(*DCRedirectionHandlerImpl).ListWorkflowExecutions\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/service/frontend/dcRedirectionHandler.go:401\ngo.temporal.io/api/workflowservice/v1._WorkflowService_ListWorkflowExecutions_Handler.func1\n\t/go/pkg/mod/go.temporal.io/api@v1.7.0/workflowservice/v1/service.pb.go:1482\ngo.temporal.io/server/common/authorization.(*interceptor).Interceptor\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/authorization/interceptor.go:152\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1116\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceCountLimitInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_count_limit.go:98\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceRateLimitInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_rate_limit.go:88\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc/interceptor.(*RateLimitInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/rate_limit.go:83\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceValidatorInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_validator.go:113\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc/interceptor.(*TelemetryInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/telemetry.go:108\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/metrics.NewServerMetricsContextInjectorInterceptor.func1\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/metrics/grpc.go:66\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc.ServiceErrorInterceptor\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/grpc.go:131\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceLogInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_logger.go:84\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1121\ngo.temporal.io/api/workflowservice/v1._WorkflowService_ListWorkflowExecutions_Handler\n\t/go/pkg/mod/go.temporal.io/api@v1.7.0/workflowservice/v1/service.pb.go:1484\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:921"}
{"level":"error","ts":"2022-01-20T13:03:56.851Z","msg":"uncategorized error","operation":"ListWorkflowExecutions","wf-namespace":"default","error":"runtime error: index out of range [1] with length 1","logging-call-at":"telemetry.go:190","stacktrace":"go.temporal.io/server/common/log.(*zapLogger).Error\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/log/zap_logger.go:142\ngo.temporal.io/server/common/rpc/interceptor.(*TelemetryInterceptor).handleError\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/telemetry.go:190\ngo.temporal.io/server/common/rpc/interceptor.(*TelemetryInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/telemetry.go:117\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/metrics.NewServerMetricsContextInjectorInterceptor.func1\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/metrics/grpc.go:66\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc.ServiceErrorInterceptor\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/grpc.go:131\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceLogInterceptor).Intercept\n\t/go/pkg/mod/go.temporal.io/server@v1.14.2/common/rpc/interceptor/namespace_logger.go:84\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1121\ngo.temporal.io/api/workflowservice/v1._WorkflowService_ListWorkflowExecutions_Handler\n\t/go/pkg/mod/go.temporal.io/api@v1.7.0/workflowservice/v1/service.pb.go:1484\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:921"}
{"level":"debug","ts":"2022-01-20T13:03:59.956Z","msg":"Membership heartbeat upserted successfully","service":"worker","address":"127.0.0.1","port":7336,"hostId":"e2af5f56-79ef-11ec-807a-0242ac120002","logging-call-at":"rpMonitor.go:163"}
{"level":"debug","ts":"2022-01-20T13:03:59.972Z","msg":"Membership heartbeat upserted successfully","service":"frontend","address":"127.0.0.1","port":7333,"hostId":"e2ac9b94-79ef-11ec-807a-0242ac120002","logging-call-at":"rpMonitor.go:163"}
```
If I start a worker with `npm start` in the `hello-world` sample, it seems to spin up and have a state of `RUNNING`. Here is the output:

```
2022-01-20T12:55:35.292Z [INFO] webpack 5.66.0 compiled successfully in 2708 ms
2022-01-20T12:55:35.294Z [INFO] Workflow bundle created { size: '0.47MB' }
2022-01-20T12:55:36.140Z [INFO] Worker state changed { state: 'RUNNING' }
```

And if I run a workflow, it seems to be registered correctly, too:

```
$ npm run workflow

> temporal-hello-world@0.1.0 workflow
> ts-node src/client.ts

Started workflow wf-id-132
```

So I'm thinking it's only the UI that has the problem? I couldn't come up with anything after this so have decided to post an issue.

### Minimal Reproduction

1. fix the typo mentioned above (temporal -> temporalite)
2. spin up the repository with VSCode devcontainer
3. go to the `hello-world` sample
4. `npm start` to start the worker
5. `npm run workflow` to register the workflow
6. browse the UI http://localhost:8080
7. the 500 error occurs repeatedly

### Environment/Versions

- OS and processor: Linux(ubuntu)
- Temporal Version: Not sure but it is the `temporalite:test` container written in the docker-compose

https://github.com/temporalio/samples-typescript/blob/9052df328b52a7d73289c9dc12e42cd2082d1a27/.devcontainer/docker-compose.yml#L40

- Are you using Docker or Kubernetes or building Temporal from source? Docker

### Additional context

If there's anything else I can share, please let me know :)

**Comment by sw-yx** [comment]
thank you for sharing! dont have time to debug this right now so hopefully somebody else can look into fixing this.. will pick it up again when GitHub Codespaces goes GA.
